parameters:
  - name: pythonVenvPath
    type: string
    default: "$(System.DefaultWorkingDirectory)/.venv"

  - name: pythonVenvCacheVersion
    type: string
    default: "1"

  - name: pythonRequirementsFileRelativePath
    type: string
    default: "requirements.txt"

  - name: ansibleRequirementsFileRelativePath
    type: string
    default: "requirements.yml"

  - name: ansibleRepository
    type: string
    default: self

  - name: ansibleRepositoryAnsiblePath
    type: string
    default: "ansible"

  - name: ansibleConfigRelativePath
    type: string
    default: "ansible.cfg"

  - name: ansibleSshConfigurations
    type: object
    default:
      - group: "all"
        user: "ansible"
        keySecretFileName: ""
        keyPassphrase: ""

  - name: ansiblePlaybooks
    type: object
    default:
      - "site.yml"

  - name: ansibleDebug
    type: boolean
    default: false

  - name: ansiblePlaybookExtraEnvironmentVariables
    type: object
    default:
      - name: ""
        value: ""

jobs:
  - job: "setupAnsible"
    displayName: "Setup Ansible"
    steps:
      - template: _templates/self_checkout.yml

      - checkout: ${{ parameters.ansibleRepository }}
        displayName: "Sparse Checkout Ansible Repository"
        path: "ansible"
        sparseCheckoutDirectories: "${{ parameters.ansibleRepositoryAnsiblePath }}"

      - task: Bash@3
        displayName: 'View Workspace Filesystem for debug'
        inputs:
          targetType: "inline"
          script: |
            echo "Structure of work folder of this pipeline:"
            tree $(Pipeline.Workspace)

      - task: Bash@3
        name: "setupEnvironment"
        displayName: "Setup Python Environment"
        inputs:
          targetType: "inline"
          script: |
            echo "##[group]Setup Python Virtual Environment"
                python3 -m venv ${{ parameters.pythonVenvPath }}
                ${{ parameters.pythonVenvPath }}/bin/pip install --upgrade pip
            echo "##[endgroup]"
          failOnStderr: true

      - task: Cache@2
        name: "cacheVenv"
        displayName: "Cache Python venv"
        inputs:
          key: 'venv | v${{ parameters.pythonVenvCacheVersion }} | "$(Agent.OS)" | $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.pythonRequirementsFileRelativePath }}'
          path: ${{ parameters.pythonVenvPath }}
          cacheHitVar: cacheRestored

      - task: Bash@3
        name: "installDependencies"
        displayName: "Install Dependencies"
        condition: ne(variables.cacheRestored, 'true')
        inputs:
          targetType: "inline"
          script: |
            echo "##[group]Install Ansible"
                ${{ parameters.pythonVenvPath }}/bin/pip install --upgrade ansible
            echo "##[endgroup]"

            if [ -f "$(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.pythonRequirementsFileRelativePath }}" ]; then
            echo "##[group]Install pip requirements"
                ${{ parameters.pythonVenvPath }}/bin/pip install --upgrade -r $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.pythonRequirementsFileRelativePath }}
            echo "##[endgroup]"
            else
                echo "No pip requirements file found at $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.pythonRequirementsFileRelativePath }}, skipping pip dependencies installation."
            fi

            if [ -f "$(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.ansibleRepositoryAnsiblePath }}" ]; then
            echo "##[group]Install ansible-galaxy collections"
                ${{ parameters.pythonVenvPath }}/bin/ansible-galaxy collection install --force -r $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.ansibleRequirementsFileRelativePath }}
            echo "##[endgroup]"
            else
                echo "No Ansible Galaxy requirements file found at $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ parameters.ansibleRequirementsFileRelativePath }}, skipping Ansible Galaxy collections installation."
            fi
          failOnStderr: true

      - ${{ each sshConfig in parameters.ansibleSshConfigurations }}:
        - task: DownloadSecureFile@1
          name: ${{ sshConfig.group }}Key
          displayName: 'Fetch ${{ sshConfig.group }} SSH Key'
          inputs:
            secureFile: "${{ sshConfig.keySecretFileName }}"

        - task: Bash@3
          name: ${{ sshConfig.group }}KeyPermissions
          displayName: 'Set Permissions for ${{ sshConfig.group }} SSH Key'
          variables:
            sshKeyPath: "$( ${{ sshConfig.group }}Key.secureFilePath )"
          inputs:
            targetType: "inline"
            script: |
              chmod 600 $(sshKeyPath)

      - ${{ each playbook in parameters.ansiblePlaybooks }}:
        - task: Bash@3
          name: "ansiblePlaybook${{ replace(replace(playbook, '.', '_'), '/', '_') }}"
          displayName: "Run Ansible Playbook: ${{ playbook }}"
          env:
            ANSIBLE_CONFIG: "${{ parameters.ansibleConfigRelativePath }}"
            DEBUG: "${{ parameters.ansibleDebug }}"
            ${{ each sshConfig in parameters.ansibleSshConfigurations }}:
              ${{ upper(sshConfig.group) }}_SSH_KEY_PATH: $( ${{ sshConfig.group }}Key.secureFilePath )
              ${{ upper(sshConfig.group) }}_SSH_USER: ${{ sshConfig.user }}
            ${{ each envVar in parameters.ansiblePlaybookExtraEnvironmentVariables }}:
              ${{ envVar.name }}: ${{ envVar.value }}
          inputs:
            targetType: "inline"
            script: |
              echo "##[group]Run Ansible Playbook: ${{ playbook }}"
                  cd $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}
                  ${{ parameters.pythonVenvPath }}/bin/ansible-playbook $(Pipeline.Workspace)/ansible/${{ parameters.ansibleRepositoryAnsiblePath }}/${{ playbook }}
              echo "##[endgroup]"
            failOnStderr: true
