parameters:
  - name: kubeconfigArtifactFileName
    type: string
    default: kubeconfig

  - name: kubeconfigArtifactName
    type: string
    default: kubeConfig

  - name: kubeconfigArtifactSourcePipeline
    type: string
    default: clusterBase

  - name: terraformRepository
    type: string
    default: self

  - name: terraformRepositoryTerraformPath
    type: string
    default: terraform

  - name: terraformValidate
    type: boolean
    default: true

  - name: terraformPlanDestroy
    type: boolean
    default: false

  - name: terraformApply
    type: boolean
    default: true

  - name: terraformBackendNamespace
    type: string
    default: kube-system

  - name: terraformBackendSuffix
    type: string
    default: terraform

  - name: terraformVariables
    type: object
    default:
      - name: ""
        value: ""

  - name: terraformExtraEnvironmentVariables
    type: object
    default:
      - name: ""
        value: ""

  - name: terraformVersion
    type: string
    default: latest

  - name: terraformApplyDependsOn
    type: object
    default: []

  - name: terraformApplyBuildReasons
    type: object
    default:
      - Manual
      - IndividualCI
      - BatchedCI
      - Schedule
      - BuildCompletion
      - ResourceTrigger

stages:
  - stage: verifyAndPlanTerraform
    displayName: "Verify and Plan Terraform"
    dependsOn: []
    jobs:
      - template: plan-terraform.yml
        parameters:
          kubeconfigArtifactFileName: ${{ parameters.kubeconfigArtifactFileName }}
          kubeconfigArtifactName: ${{ parameters.kubeconfigArtifactName }}
          kubeconfigArtifactSourcePipeline: ${{ parameters.kubeconfigArtifactSourcePipeline }}
          terraformRepository: ${{ parameters.terraformRepository }}
          terraformRepositoryTerraformPath: ${{ parameters.terraformRepositoryTerraformPath }}
          terraformValidate: ${{ parameters.terraformValidate }}
          terraformPlanDestroy: ${{ parameters.terraformPlanDestroy }}
          terraformBackendNamespace: ${{ parameters.terraformBackendNamespace }}
          terraformBackendSuffix: ${{ parameters.terraformBackendSuffix }}
          terraformVariables: ${{ parameters.terraformVariables }}
          terraformExtraEnvironmentVariables: ${{ parameters.terraformExtraEnvironmentVariables }}
          terraformVersion: ${{ parameters.terraformVersion }}

  - stage: applyTerraform
    displayName: "Apply Planned Terraform"
    dependsOn:
      - verifyAndPlanTerraform
      - ${{ each dep in parameters.terraformApplyDependsOn }}:
        - ${{ dep }}
    condition: >-
      and(
        eq('${{ parameters.terraformApply }}', 'true'),
        in(dependencies.verifyAndPlanTerraform.result, 'Succeeded'),
        in(variables['Build.Reason'], '${{ join(', ', parameters.terraformApplyBuildReasons) }}')
      )
    jobs:
      - template: apply-terraform.yml
        parameters:
          kubeconfigArtifactFileName: ${{ parameters.kubeconfigArtifactFileName }}
          kubeconfigArtifactName: ${{ parameters.kubeconfigArtifactName }}
          kubeconfigArtifactSourcePipeline: ${{ parameters.kubeconfigArtifactSourcePipeline }}
          terraformRepository: ${{ parameters.terraformRepository }}
          terraformRepositoryTerraformPath: ${{ parameters.terraformRepositoryTerraformPath }}
          terraformBackendNamespace: ${{ parameters.terraformBackendNamespace }}
          terraformBackendSuffix: ${{ parameters.terraformBackendSuffix }}
          terraformVariables: ${{ parameters.terraformVariables }}
          terraformExtraEnvironmentVariables: ${{ parameters.terraformExtraEnvironmentVariables }}
          terraformVersion: ${{ parameters.terraformVersion }}
